"""Generate the Clerk-compatible identity migration from the live schema.

Why a generator rather than a hand-written migration: 28 RLS policies have to be
rewritten, and a typo in an RLS policy is a data leak, not a bug. Reading the
deployed definitions and substituting the identity function keeps every condition
byte-for-byte what was already verified.

The substitution is deliberately narrow — `auth.uid()` -> `public.current_user_id()`
and nothing else.

Usage:
    python supabase/scripts/generate_clerk_migration.py
"""

from __future__ import annotations

import pathlib
import re
import sys

import psycopg2

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEST = ROOT / "supabase" / "migrations" / "20260920000001_clerk_compatible_identity.sql"


def read_env() -> dict[str, str]:
    env: dict[str, str] = {}
    for line in (ROOT / "backend" / ".env").read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.strip().startswith("#"):
            key, value = line.split("=", 1)
            env[key.strip()] = value.strip()
    return env


def rewrite(condition: str) -> str:
    """Point identity at the TEXT helper instead of the uuid-casting one."""
    return re.sub(r"auth\.uid\(\)", "public.current_user_id()", condition)


HEADER = """-- ===========================================================================
-- Clerk-compatible identity
--
-- Lets the schema accept a Clerk subject as well as a Supabase one, WITHOUT
-- breaking Supabase Auth. The app keeps working throughout — see
-- `docs/clerk-migration-assessment.md`.
--
-- Why this is needed: Supabase defines
--     auth.uid() -> coalesce(... ->> 'sub')::uuid
-- so it CASTS the JWT subject to uuid. Clerk subjects are strings
-- (`user_2abc...`), which makes every call site RAISE
-- `invalid input syntax for type uuid` — they do not merely mismatch.
--
-- The fix is a helper returning the raw subject as TEXT, with no cast, so it is
-- correct for both issuers:
--     Supabase -> 'a1b2c3d4-...'   (a uuid, as text)
--     Clerk    -> 'user_2abc...'
--
-- Generated by `supabase/scripts/generate_clerk_migration.py` from the deployed
-- policy definitions. Do not hand-edit the policy block.
--
-- DEPENDS ON: 20260915000003_rls_policies.sql
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Identity helper — TEXT, no cast, issuer-agnostic
-- ---------------------------------------------------------------------------
create or replace function public.current_user_id()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  );
$$;

comment on function public.current_user_id() is
  'JWT subject as TEXT, for either Supabase Auth (uuid) or Clerk (string). '
  'Prefer this over auth.uid(), which casts to uuid and therefore rejects a '
  'Clerk subject outright.';

revoke execute on function public.current_user_id() from public, anon;
grant execute on function public.current_user_id() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 2. Drop every policy that touches an identity column
--
-- These must go BEFORE the type changes below. Postgres refuses to alter a
-- column's type while a policy depends on it:
--
--   ERROR: cannot alter type of a column used in a policy definition
--   DETAIL: policy users_select_own_or_admin on table users depends on column "id"
--
-- They are recreated unchanged in section 5.
-- ---------------------------------------------------------------------------
"""

POLICY_ALTER = """-- ---------------------------------------------------------------------------
-- 3. Widen the identity columns to text
--
-- Three explicit phases, because the dependencies are circular:
--
--   * `users.id` cannot change type while a child FK still points at it
--   * a child `user_id` cannot change type while its FK still exists
--
-- So: drop every FK, alter every column, then recreate the FKs. Doing it
-- per-table (drop/alter/add, then next table) fails on the second table with
--     DETAIL: Key columns "user_id" and "id" are of incompatible types
-- because `users.id` is already text while that table's column is still uuid.
--
-- The FK to auth.users is dropped for good: with Clerk there IS no auth.users
-- row — Clerk is the identity system and Supabase's auth schema stays empty. The
-- FK would have no parent, and on_auth_user_created would never fire, so profile
-- rows have to be created by a Clerk webhook or a lazy upsert instead.
-- ---------------------------------------------------------------------------
alter table public.users drop constraint if exists users_id_fkey;
"""

FK_RECREATE_HEADER = """
-- Recreate the child foreign keys against the widened parent.
"""

ROLE_HELPER = """-- ---------------------------------------------------------------------------
-- 4. `public_profiles` — argument and return types widen with the column
--
-- It takes `uuid[]` and returns `id uuid`; both now disagree with
-- `public.users.id`. Left alone, every community feed read fails with
--     HINT: No operator matches the given name and argument types.
-- The body is unchanged — only the types move.
--
-- The narrow disclosure (id, name, role — never email, phone, region or crops)
-- is preserved exactly. See DECISIONS.md §7.1.
-- ---------------------------------------------------------------------------
drop function if exists public.public_profiles(uuid[]);

create or replace function public.public_profiles(user_ids text[])
returns table (
  id   text,
  name text,
  role text
)
language sql
security definer
stable
set search_path = public, pg_temp
as $$
  select u.id, u.name, u.role
  from public.users u
  where u.id = any(user_ids);
$$;

comment on function public.public_profiles(text[]) is
  'Public display fields (id, name, role) for community authors. Deliberately '
  'narrow: never expose email, phone, region or crops. See DECISIONS.md §7.1.';

revoke all on function public.public_profiles(text[]) from public;
revoke all on function public.public_profiles(text[]) from anon;
grant execute on function public.public_profiles(text[]) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Role helpers read the new identity function
-- ---------------------------------------------------------------------------
create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select u.role from public.users u where u.id = public.current_user_id();
$$;

-- ---------------------------------------------------------------------------
-- 6. Policies, recreated
--
-- Regenerated from the deployed definitions; the only change is the identity
-- function. Every other condition is byte-for-byte what was already verified by
-- the RLS suites.
-- ---------------------------------------------------------------------------
"""

FOOTER = """-- ---------------------------------------------------------------------------
-- 7. Verify
--
-- No policy may still call auth.uid(), or a Clerk user would raise on every
-- query. Failing loudly here is better than discovering it in production.
-- ---------------------------------------------------------------------------
do $$
declare
  remaining int;
begin
  select count(*) into remaining
  from pg_policies
  where schemaname = 'public'
    and (coalesce(qual, '') like '%auth.uid()%'
         or coalesce(with_check, '') like '%auth.uid()%');

  if remaining > 0 then
    raise exception
      'Clerk migration incomplete: % policy/policies still call auth.uid()',
      remaining;
  end if;
end $$;
"""


def main() -> int:
    conn = psycopg2.connect(read_env()["DATABASE_URL"])
    cur = conn.cursor()

    cur.execute(
        """
        select tablename, policyname, cmd, permissive, roles, qual, with_check
        from pg_policies
        where schemaname = 'public'
          and (coalesce(qual, '') like '%auth.uid()%'
               or coalesce(with_check, '') like '%auth.uid()%')
        order by tablename, policyname
        """
    )
    policies = cur.fetchall()

    cur.execute(
        """
        select tc.table_name, kcu.column_name, tc.constraint_name
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on kcu.constraint_name = tc.constraint_name
        join information_schema.constraint_column_usage ccu
          on ccu.constraint_name = tc.constraint_name
        where tc.constraint_type = 'FOREIGN KEY'
          and ccu.table_name = 'users'
          and tc.table_schema = 'public'
        order by tc.table_name
        """
    )
    fks = cur.fetchall()
    conn.close()

    out: list[str] = [HEADER]

    # Phase 1 — drop policies (Postgres will not alter a column a policy uses).
    for table, policy, *_ in policies:
        out.append(f"drop policy if exists {policy} on public.{table};")
    out.append("")
    out.append(POLICY_ALTER)

    # Phase 2 — drop EVERY child FK before touching any column type.
    for table, _column, constraint in fks:
        out.append(f"alter table public.{table} drop constraint if exists {constraint};")
    out.append("")

    # Phase 3 — alter every column, now that nothing depends on them.
    out.append("alter table public.users alter column id type text;")
    out.append("")
    out.append(
        "comment on column public.users.id is\n"
        "  'Identity subject: a Supabase uuid or a Clerk user id, as TEXT. No FK '\n"
        "  'to auth.users — see the Clerk migration notes.';"
    )
    out.append("")
    for table, column, _constraint in fks:
        out.append(f"alter table public.{table} alter column {column} type text;")
    out.append(FK_RECREATE_HEADER)

    # Phase 4 — recreate the FKs against the widened parent.
    for table, column, constraint in fks:
        out.append(
            f"alter table public.{table} add constraint {constraint} "
            f"foreign key ({column}) references public.users (id) on delete cascade;"
        )
    out.append("")

    out.append(ROLE_HELPER)

    for table, policy, cmd, permissive, roles, qual, with_check in policies:
        role_list = ", ".join(roles) if isinstance(roles, list) else str(roles)
        stmt = f"create policy {policy} on public.{table}"
        if permissive and permissive.upper() != "PERMISSIVE":
            stmt += f"\n  as {permissive.lower()}"
        stmt += f"\n  for {cmd.lower()}"
        stmt += f"\n  to {role_list}"
        if qual:
            stmt += f"\n  using ({rewrite(qual)})"
        if with_check:
            stmt += f"\n  with check ({rewrite(with_check)})"
        out.append(stmt + ";")
        out.append("")

    out.append(FOOTER)

    DEST.write_text("\n".join(out), encoding="utf-8")
    print(f"  wrote {DEST.relative_to(ROOT)}")
    print(f"  {len(policies)} policies, {len(fks)} foreign keys")
    print(f"  {len(DEST.read_text(encoding='utf-8').splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
