"""Pydantic models for the disease-detection endpoints (Phase 4).

Note which fields are *stored* and which are *derived*. Only `confidence_score`
and `predicted_disease` are persisted; the band, the expert-confirmation flag and
the healthy flag are computed on read so they can never drift out of sync with
the stored score.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from app.models.labels import (
    CONFIDENCE_HIGH_THRESHOLD,
    CONFIDENCE_LOW_THRESHOLD,
    CONFIDENCE_UNRELIABLE_THRESHOLD,
)


def confidence_band(score: float) -> str:
    if score >= CONFIDENCE_HIGH_THRESHOLD:
        return "high"
    if score >= CONFIDENCE_LOW_THRESHOLD:
        return "medium"
    return "low"


class AlternativeOut(BaseModel):
    """A runner-up class the model considered."""

    disease_name: str
    display_name: str
    confidence_score: float


class SolutionOut(BaseModel):
    """One curated Natural or Traditional solution.

    Never generated by the LLM — always a row from the `solutions` table.
    """

    model_config = ConfigDict(extra="ignore")

    id: str
    solution_type: str
    title: str
    description: str
    source_name: str
    source_url: str | None = None
    region_specific: str | None = None
    verified: bool = False


class SolutionsOut(BaseModel):
    """The two sections rendered on the diagnosis screen.

    `complete` is False when one of the sections is empty, so the UI can say so
    honestly instead of showing a blank panel.
    """

    natural: list[SolutionOut] = Field(default_factory=list)
    traditional: list[SolutionOut] = Field(default_factory=list)
    total: int = 0
    complete: bool = False


class DiagnosisOut(BaseModel):
    """A stored diagnosis, plus everything the result screen needs to render it."""

    model_config = ConfigDict(extra="ignore")

    id: str
    user_id: str

    # The stored object path (never a public URL — the bucket is private).
    image_url: str
    # Short-lived signed URL, minted on read. May be None if signing failed.
    image_signed_url: str | None = None

    crop_type: str
    predicted_disease: str
    confidence_score: float = Field(ge=0, le=1)
    symptoms_summary: str | None = None
    model_version: str
    created_at: str

    # ---- Derived, never stored -------------------------------------------
    confidence_band: str
    needs_expert_confirmation: bool
    is_reliable: bool
    is_healthy: bool

    # Only populated on the POST response, since alternatives are not persisted.
    alternatives: list[AlternativeOut] | None = None

    # Matched from the curated knowledge base (Phase 5). Never LLM-generated.
    solutions: SolutionsOut | None = None

    @classmethod
    def from_row(
        cls,
        row: dict,
        *,
        image_signed_url: str | None = None,
        alternatives: list[AlternativeOut] | None = None,
        solutions: SolutionsOut | None = None,
    ) -> DiagnosisOut:
        """Build a response from a `diagnoses` row."""
        score = float(row["confidence_score"])
        disease = row["predicted_disease"]
        return cls(
            id=row["id"],
            user_id=row["user_id"],
            image_url=row["image_url"],
            image_signed_url=image_signed_url,
            crop_type=row["crop_type"],
            predicted_disease=disease,
            confidence_score=score,
            symptoms_summary=row.get("symptoms_summary"),
            model_version=row["model_version"],
            created_at=str(row["created_at"]),
            confidence_band=confidence_band(score),
            # Must mirror `models.inference.predict` exactly — this path rebuilds
            # the flags when reading a stored diagnosis, so a divergence here
            # would make a result change shape between the response that created
            # it and the page that later displays it. Low band only; see the
            # comment in inference.py for why it is not gated on HIGH.
            needs_expert_confirmation=score < CONFIDENCE_LOW_THRESHOLD,
            is_reliable=score >= CONFIDENCE_UNRELIABLE_THRESHOLD,
            is_healthy=disease.endswith(" - Healthy"),
            alternatives=alternatives,
            solutions=solutions,
        )

    @staticmethod
    def solutions_from(grouped) -> SolutionsOut:
        """Convert a `SolutionsForDisease` into the response shape."""
        return SolutionsOut(
            natural=[
                SolutionOut(
                    id=s.id,
                    solution_type=s.solution_type,
                    title=s.title,
                    description=s.description,
                    source_name=s.source_name,
                    source_url=s.source_url,
                    region_specific=s.region_specific,
                    verified=s.verified,
                )
                for s in grouped.natural
            ],
            traditional=[
                SolutionOut(
                    id=s.id,
                    solution_type=s.solution_type,
                    title=s.title,
                    description=s.description,
                    source_name=s.source_name,
                    source_url=s.source_url,
                    region_specific=s.region_specific,
                    verified=s.verified,
                )
                for s in grouped.traditional
            ],
            total=grouped.total,
            complete=grouped.is_complete,
        )


class DiagnosisListOut(BaseModel):
    """Dashboard history."""

    items: list[DiagnosisOut]
    total: int


class ModelInfoOut(BaseModel):
    """What the API knows about the currently loaded model."""

    loaded: bool
    version: str | None = None
    architecture: str | None = None
    num_classes: int | None = None
    trained_at: str | None = None
    classes: list[str] = Field(default_factory=list)
    metrics: dict = Field(default_factory=dict)
    error: str | None = None
