-- ===========================================================================
-- Clerk-compatible identity
--
-- Lets the schema accept a Clerk subject as well as a Supabase one, WITHOUT
-- breaking Supabase Auth. The app keeps working throughout — see
-- `docs/clerk-migration-assessment.md`.
--
-- Why this is needed: Supabase defines
--     auth.uid() -> coalesce(... ->> 'sub')::uuid
-- so it CASTS the JWT subject to uuid. Clerk subjects are strings
-- (`user_2abc...`), which makes every call site RAISE
-- `invalid input syntax for type uuid` — they do not merely mismatch.
--
-- The fix is a helper returning the raw subject as TEXT, with no cast, so it is
-- correct for both issuers:
--     Supabase -> 'a1b2c3d4-...'   (a uuid, as text)
--     Clerk    -> 'user_2abc...'
--
-- Generated by `supabase/scripts/generate_clerk_migration.py` from the deployed
-- policy definitions. Do not hand-edit the policy block.
--
-- DEPENDS ON: 20260915000003_rls_policies.sql
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Identity helper — TEXT, no cast, issuer-agnostic
-- ---------------------------------------------------------------------------
create or replace function public.current_user_id()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  );
$$;

comment on function public.current_user_id() is
  'JWT subject as TEXT, for either Supabase Auth (uuid) or Clerk (string). '
  'Prefer this over auth.uid(), which casts to uuid and therefore rejects a '
  'Clerk subject outright.';

revoke execute on function public.current_user_id() from public, anon;
grant execute on function public.current_user_id() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 2. Drop every policy that touches an identity column
--
-- These must go BEFORE the type changes below. Postgres refuses to alter a
-- column's type while a policy depends on it:
--
--   ERROR: cannot alter type of a column used in a policy definition
--   DETAIL: policy users_select_own_or_admin on table users depends on column "id"
--
-- They are recreated unchanged in section 5.
-- ---------------------------------------------------------------------------

drop policy if exists assistant_conversations_delete_own on public.assistant_conversations;
drop policy if exists assistant_conversations_insert_own on public.assistant_conversations;
drop policy if exists assistant_conversations_select_own on public.assistant_conversations;
drop policy if exists assistant_conversations_update_own on public.assistant_conversations;
drop policy if exists assistant_messages_delete_own on public.assistant_messages;
drop policy if exists assistant_messages_insert_own on public.assistant_messages;
drop policy if exists assistant_messages_select_own on public.assistant_messages;
drop policy if exists comments_delete_own_or_staff on public.comments;
drop policy if exists comments_insert_authenticated on public.comments;
drop policy if exists comments_update_own_or_staff on public.comments;
drop policy if exists communities_delete_owner_or_admin on public.communities;
drop policy if exists communities_insert_authenticated on public.communities;
drop policy if exists communities_update_owner_or_admin on public.communities;
drop policy if exists community_members_delete_self on public.community_members;
drop policy if exists community_members_insert_self on public.community_members;
drop policy if exists diagnoses_delete_own on public.diagnoses;
drop policy if exists diagnoses_insert_own on public.diagnoses;
drop policy if exists diagnoses_select_own on public.diagnoses;
drop policy if exists diagnoses_update_own on public.diagnoses;
drop policy if exists post_likes_delete_self on public.post_likes;
drop policy if exists post_likes_insert_self on public.post_likes;
drop policy if exists posts_delete_own_or_staff on public.posts;
drop policy if exists posts_insert_authenticated on public.posts;
drop policy if exists posts_update_own_or_staff on public.posts;
drop policy if exists users_delete_own_or_admin on public.users;
drop policy if exists users_insert_self on public.users;
drop policy if exists users_select_own_or_admin on public.users;
drop policy if exists users_update_own_or_admin on public.users;

-- ---------------------------------------------------------------------------
-- 3. Widen the identity columns to text
--
-- Three explicit phases, because the dependencies are circular:
--
--   * `users.id` cannot change type while a child FK still points at it
--   * a child `user_id` cannot change type while its FK still exists
--
-- So: drop every FK, alter every column, then recreate the FKs. Doing it
-- per-table (drop/alter/add, then next table) fails on the second table with
--     DETAIL: Key columns "user_id" and "id" are of incompatible types
-- because `users.id` is already text while that table's column is still uuid.
--
-- The FK to auth.users is dropped for good: with Clerk there IS no auth.users
-- row — Clerk is the identity system and Supabase's auth schema stays empty. The
-- FK would have no parent, and on_auth_user_created would never fire, so profile
-- rows have to be created by a Clerk webhook or a lazy upsert instead.
-- ---------------------------------------------------------------------------
alter table public.users drop constraint if exists users_id_fkey;

alter table public.assistant_conversations drop constraint if exists assistant_conversations_user_id_fkey;
alter table public.comments drop constraint if exists comments_user_id_fkey;
alter table public.communities drop constraint if exists communities_created_by_fkey;
alter table public.community_members drop constraint if exists community_members_user_id_fkey;
alter table public.diagnoses drop constraint if exists diagnoses_user_id_fkey;
alter table public.post_likes drop constraint if exists post_likes_user_id_fkey;
alter table public.posts drop constraint if exists posts_user_id_fkey;

alter table public.users alter column id type text;

comment on column public.users.id is
  'Identity subject: a Supabase uuid or a Clerk user id, as TEXT. No FK '
  'to auth.users — see the Clerk migration notes.';

alter table public.assistant_conversations alter column user_id type text;
alter table public.comments alter column user_id type text;
alter table public.communities alter column created_by type text;
alter table public.community_members alter column user_id type text;
alter table public.diagnoses alter column user_id type text;
alter table public.post_likes alter column user_id type text;
alter table public.posts alter column user_id type text;

-- Recreate the child foreign keys against the widened parent.

alter table public.assistant_conversations add constraint assistant_conversations_user_id_fkey foreign key (user_id) references public.users (id) on delete cascade;
alter table public.comments add constraint comments_user_id_fkey foreign key (user_id) references public.users (id) on delete cascade;
alter table public.communities add constraint communities_created_by_fkey foreign key (created_by) references public.users (id) on delete cascade;
alter table public.community_members add constraint community_members_user_id_fkey foreign key (user_id) references public.users (id) on delete cascade;
alter table public.diagnoses add constraint diagnoses_user_id_fkey foreign key (user_id) references public.users (id) on delete cascade;
alter table public.post_likes add constraint post_likes_user_id_fkey foreign key (user_id) references public.users (id) on delete cascade;
alter table public.posts add constraint posts_user_id_fkey foreign key (user_id) references public.users (id) on delete cascade;

-- ---------------------------------------------------------------------------
-- 4. `public_profiles` — argument and return types widen with the column
--
-- It takes `uuid[]` and returns `id uuid`; both now disagree with
-- `public.users.id`. Left alone, every community feed read fails with
--     HINT: No operator matches the given name and argument types.
-- The body is unchanged — only the types move.
--
-- The narrow disclosure (id, name, role — never email, phone, region or crops)
-- is preserved exactly. See DECISIONS.md §7.1.
-- ---------------------------------------------------------------------------
drop function if exists public.public_profiles(uuid[]);

create or replace function public.public_profiles(user_ids text[])
returns table (
  id   text,
  name text,
  role text
)
language sql
security definer
stable
set search_path = public, pg_temp
as $$
  select u.id, u.name, u.role
  from public.users u
  where u.id = any(user_ids);
$$;

comment on function public.public_profiles(text[]) is
  'Public display fields (id, name, role) for community authors. Deliberately '
  'narrow: never expose email, phone, region or crops. See DECISIONS.md §7.1.';

revoke all on function public.public_profiles(text[]) from public;
revoke all on function public.public_profiles(text[]) from anon;
grant execute on function public.public_profiles(text[]) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Role helpers read the new identity function
-- ---------------------------------------------------------------------------
create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select u.role from public.users u where u.id = public.current_user_id();
$$;

-- ---------------------------------------------------------------------------
-- 6. Policies, recreated
--
-- Regenerated from the deployed definitions; the only change is the identity
-- function. Every other condition is byte-for-byte what was already verified by
-- the RLS suites.
-- ---------------------------------------------------------------------------

create policy assistant_conversations_delete_own on public.assistant_conversations
  for delete
  to authenticated
  using ((user_id = public.current_user_id()));

create policy assistant_conversations_insert_own on public.assistant_conversations
  for insert
  to authenticated
  with check ((user_id = public.current_user_id()));

create policy assistant_conversations_select_own on public.assistant_conversations
  for select
  to authenticated
  using ((user_id = public.current_user_id()));

create policy assistant_conversations_update_own on public.assistant_conversations
  for update
  to authenticated
  using ((user_id = public.current_user_id()))
  with check ((user_id = public.current_user_id()));

create policy assistant_messages_delete_own on public.assistant_messages
  for delete
  to authenticated
  using ((EXISTS ( SELECT 1
   FROM assistant_conversations c
  WHERE ((c.id = assistant_messages.conversation_id) AND (c.user_id = public.current_user_id())))));

create policy assistant_messages_insert_own on public.assistant_messages
  for insert
  to authenticated
  with check ((EXISTS ( SELECT 1
   FROM assistant_conversations c
  WHERE ((c.id = assistant_messages.conversation_id) AND (c.user_id = public.current_user_id())))));

create policy assistant_messages_select_own on public.assistant_messages
  for select
  to authenticated
  using ((EXISTS ( SELECT 1
   FROM assistant_conversations c
  WHERE ((c.id = assistant_messages.conversation_id) AND (c.user_id = public.current_user_id())))));

create policy comments_delete_own_or_staff on public.comments
  for delete
  to authenticated
  using (((user_id = public.current_user_id()) OR is_moderator_or_admin()));

create policy comments_insert_authenticated on public.comments
  for insert
  to authenticated
  with check ((user_id = public.current_user_id()));

create policy comments_update_own_or_staff on public.comments
  for update
  to authenticated
  using (((user_id = public.current_user_id()) OR is_moderator_or_admin()))
  with check (((user_id = public.current_user_id()) OR is_moderator_or_admin()));

create policy communities_delete_owner_or_admin on public.communities
  for delete
  to authenticated
  using (((created_by = public.current_user_id()) OR is_admin()));

create policy communities_insert_authenticated on public.communities
  for insert
  to authenticated
  with check ((created_by = public.current_user_id()));

create policy communities_update_owner_or_admin on public.communities
  for update
  to authenticated
  using (((created_by = public.current_user_id()) OR is_admin()))
  with check (((created_by = public.current_user_id()) OR is_admin()));

create policy community_members_delete_self on public.community_members
  for delete
  to authenticated
  using ((user_id = public.current_user_id()));

create policy community_members_insert_self on public.community_members
  for insert
  to authenticated
  with check ((user_id = public.current_user_id()));

create policy diagnoses_delete_own on public.diagnoses
  for delete
  to authenticated
  using ((user_id = public.current_user_id()));

create policy diagnoses_insert_own on public.diagnoses
  for insert
  to authenticated
  with check ((user_id = public.current_user_id()));

create policy diagnoses_select_own on public.diagnoses
  for select
  to authenticated
  using ((user_id = public.current_user_id()));

create policy diagnoses_update_own on public.diagnoses
  for update
  to authenticated
  using ((user_id = public.current_user_id()))
  with check ((user_id = public.current_user_id()));

create policy post_likes_delete_self on public.post_likes
  for delete
  to authenticated
  using ((user_id = public.current_user_id()));

create policy post_likes_insert_self on public.post_likes
  for insert
  to authenticated
  with check ((user_id = public.current_user_id()));

create policy posts_delete_own_or_staff on public.posts
  for delete
  to authenticated
  using (((user_id = public.current_user_id()) OR is_moderator_or_admin()));

create policy posts_insert_authenticated on public.posts
  for insert
  to authenticated
  with check ((user_id = public.current_user_id()));

create policy posts_update_own_or_staff on public.posts
  for update
  to authenticated
  using (((user_id = public.current_user_id()) OR is_moderator_or_admin()))
  with check (((user_id = public.current_user_id()) OR is_moderator_or_admin()));

create policy users_delete_own_or_admin on public.users
  for delete
  to authenticated
  using (((id = public.current_user_id()) OR is_admin()));

create policy users_insert_self on public.users
  for insert
  to authenticated
  with check ((id = public.current_user_id()));

create policy users_select_own_or_admin on public.users
  for select
  to authenticated
  using (((id = public.current_user_id()) OR is_admin()));

create policy users_update_own_or_admin on public.users
  for update
  to authenticated
  using (((id = public.current_user_id()) OR is_admin()))
  with check (((id = public.current_user_id()) OR is_admin()));

-- ---------------------------------------------------------------------------
-- 7. Verify
--
-- No policy may still call auth.uid(), or a Clerk user would raise on every
-- query. Failing loudly here is better than discovering it in production.
-- ---------------------------------------------------------------------------
do $$
declare
  remaining int;
begin
  select count(*) into remaining
  from pg_policies
  where schemaname = 'public'
    and (coalesce(qual, '') like '%auth.uid()%'
         or coalesce(with_check, '') like '%auth.uid()%');

  if remaining > 0 then
    raise exception
      'Clerk migration incomplete: % policy/policies still call auth.uid()',
      remaining;
  end if;
end $$;
